### ISSUE TITLE
getting a lot of timeouts

### ISSUE THREAD

**Issue by InteNs** [snok/container-retention-policy#18]
Hey there, I've been trying to set this up in our workflows but i'm getting a lot of timeout errors, I might be trying to delete way too many images, we have quiet the backlog of images to delete.

attached is the traceback:

```
2022-01-25T20:24:10.3791843Z Traceback (most recent call last):
2022-01-25T20:24:10.3792184Z Deleted old image: avatar:1766504
2022-01-25T20:24:10.3793005Z   File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 108, in _call_sslobject_method
2022-01-25T20:24:10.3793404Z     result = func(*args)
2022-01-25T20:24:10.3793658Z Deleted old image: avatar:2010207
2022-01-25T20:24:10.3793932Z Deleted old image: avatar:1889366
2022-01-25T20:24:10.3844760Z   File "/usr/local/lib/python3.10/ssl.py", line 916, in read
2022-01-25T20:24:10.3847890Z     v = self._sslobj.read(len)
2022-01-25T20:24:10.3850940Z ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2536)
2022-01-25T20:24:10.3852851Z 
2022-01-25T20:24:10.3853542Z During handling of the above exception, another exception occurred:
2022-01-25T20:24:10.3854028Z 
2022-01-25T20:24:10.3854387Z Traceback (most recent call last):
2022-01-25T20:24:10.3855525Z   File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 31, in read
2022-01-25T20:24:10.3856085Z     return await self._stream.receive(max_bytes=max_bytes)
2022-01-25T20:24:10.3856944Z   File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 171, in receive
2022-01-25T20:24:10.3858222Z     data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
2022-01-25T20:24:10.3859199Z   File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 115, in _call_sslobject_method
2022-01-25T20:24:10.3859787Z     data = await self.transport_stream.receive()
2022-01-25T20:24:10.3860410Z   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1105, in receive
2022-01-25T20:24:10.3860903Z     await self._protocol.read_event.wait()
2022-01-25T20:24:10.3861350Z   File "/usr/local/lib/python3.10/asyncio/locks.py", line 213, in wait
2022-01-25T20:24:10.3861736Z     await fut
2022-01-25T20:24:10.3862115Z asyncio.exceptions.CancelledError
2022-01-25T20:24:10.3862421Z 
2022-01-25T20:24:10.3862806Z During handling of the above exception, another exception occurred:
2022-01-25T20:24:10.3863260Z 
2022-01-25T20:24:10.3863617Z Traceback (most recent call last):
2022-01-25T20:24:10.3864224Z   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
2022-01-25T20:24:10.3864655Z     yield
2022-01-25T20:24:10.3865204Z   File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 29, in read
2022-01-25T20:24:10.3865671Z     with anyio.fail_after(timeout):
2022-01-25T20:24:10.3866227Z   File "/usr/local/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 103, in __exit__
2022-01-25T20:24:10.3866674Z     raise TimeoutError
2022-01-25T20:24:10.3867038Z TimeoutError
2022-01-25T20:24:10.3867298Z 
2022-01-25T20:24:10.3867688Z During handling of the above exception, another exception occurred:
2022-01-25T20:24:10.3868022Z 
2022-01-25T20:24:10.3868364Z Traceback (most recent call last):
2022-01-25T20:24:10.3868997Z   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
2022-01-25T20:24:10.3869441Z     yield
2022-01-25T20:24:10.3870028Z   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
2022-01-25T20:24:10.3870702Z     resp = await self._pool.handle_async_request(req)
2022-01-25T20:24:10.3871381Z   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 244, in handle_async_request
2022-01-25T20:24:10.3871840Z     raise exc
2022-01-25T20:24:10.3872436Z   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 228, in handle_async_request
2022-01-25T20:24:10.3872959Z     response = await connection.handle_async_request(request)
2022-01-25T20:24:10.3873618Z   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
2022-01-25T20:24:10.3874194Z     return await self._connection.handle_async_request(request)
2022-01-25T20:24:10.3874950Z   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 102, in handle_async_request
2022-01-25T20:24:10.3875375Z     raise exc
2022-01-25T20:24:10.3875920Z   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 81, in handle_async_request
2022-01-25T20:24:10.3876361Z     ) = await self._receive_response_headers(**kwargs)
2022-01-25T20:24:10.3876926Z   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 143, in _receive_response_headers
2022-01-25T20:24:10.3877370Z     event = await self._receive_event(timeout=timeout)
2022-01-25T20:24:10.3877934Z   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 172, in _receive_event
2022-01-25T20:24:10.3882949Z     data = await self._network_stream.read(
2022-01-25T20:24:10.3890311Z   File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 28, in read
2022-01-25T20:24:10.3891259Z     with map_exceptions(exc_map):
2022-01-25T20:24:10.3891580Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2022-01-25T20:24:10.3892123Z     self.gen.throw(typ, value, traceback)
2022-01-25T20:24:10.3892866Z   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
2022-01-25T20:24:10.3893180Z     raise to_exc(exc)
2022-01-25T20:24:10.3893400Z httpcore.ReadTimeout
2022-01-25T20:24:10.3893543Z 
2022-01-25T20:24:10.3893842Z The above exception was the direct cause of the following exception:
2022-01-25T20:24:10.3894038Z 
2022-01-25T20:24:10.3894224Z Traceback (most recent call last):
2022-01-25T20:24:10.3894474Z   File "/main.py", line 355, in <module>
2022-01-25T20:24:10.3894720Z     asyncio.run(main(*argv[1:]))
2022-01-25T20:24:10.3894998Z   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2022-01-25T20:24:10.3895294Z     return loop.run_until_complete(main)
2022-01-25T20:24:10.3895614Z   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
2022-01-25T20:24:10.3895899Z     return future.result()
2022-01-25T20:24:10.3896132Z   File "/main.py", line 351, in main
2022-01-25T20:24:10.3896361Z     await asyncio.gather(*tasks)
2022-01-25T20:24:10.3896641Z   File "/main.py", line 290, in get_and_delete_old_versions
2022-01-25T20:24:10.3896908Z     await asyncio.gather(*tasks)
2022-01-25T20:24:10.3897149Z   File "/main.py", line 154, in delete_package
2022-01-25T20:24:10.3899753Z     return await delete_org_package_versions(
2022-01-25T20:24:10.3900052Z   File "/main.py", line 110, in delete_org_package_versions
2022-01-25T20:24:10.3900328Z     response = await http_client.delete(url)
2022-01-25T20:24:10.3900816Z   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1934, in delete
2022-01-25T20:24:10.3901129Z     return await self.request(
2022-01-25T20:24:10.3901533Z   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1513, in request
2022-01-25T20:24:10.3901913Z     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
2022-01-25T20:24:10.3902409Z   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1600, in send
2022-01-25T20:24:10.3902718Z     response = await self._send_handling_auth(
2022-01-25T20:24:10.3903176Z   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
2022-01-25T20:24:10.3903694Z     response = await self._send_handling_redirects(
2022-01-25T20:24:10.3904188Z   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
2022-01-25T20:24:10.3913258Z     response = await self._send_single_request(request)
2022-01-25T20:24:10.3914350Z   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_single_request
2022-01-25T20:24:10.3915021Z     response = await transport.handle_async_request(request)
2022-01-25T20:24:10.3915941Z   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 307, in handle_async_request
2022-01-25T20:24:10.3917924Z     with map_httpcore_exceptions():
2022-01-25T20:24:10.3919260Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2022-01-25T20:24:10.3921837Z     self.gen.throw(typ, value, traceback)
2022-01-25T20:24:10.3923355Z   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
2022-01-25T20:24:10.3925278Z     raise mapped_exc(message) from exc
2022-01-25T20:24:10.3926469Z httpx.ReadTimeout
2022-01-25T20:24:10.6749211Z Cleaning up orphan processes
```

**Comment by sondrelg** [comment]
Yes I've noticed this when deleting more than a certain amount of images. It should still delete `n` amount of images each time you retry the actions, but I'll admit this isn't a great side-effect.

Would you be interested in trying to investigate how to handle it @InteNs? A PR would be very welcome if so 👏

**Comment by InteNs** [comment]
hmm, im wondering if there would we an option in whatever http library this action is using for the default timeout?

i'm not sure we can fix this reliably, the next hurdle is going to be the rate limits for the github api probably...

**Comment by sondrelg** [comment]
I think I know what it is actually. HTTPX has a max-connections limit of 100 by default. I'm fairly certain this the error you'll see as soon as you exceed the max threshold. 

Some sort of queue or mechanism to not run more than 100 connections at once should fix the issue.

**Comment by sondrelg** [comment]
Do you still have lots of images to delete (ideally more than 100) @InteNs? If so, it would be great if you could test #19. All you need to do is set `<action-name>@4d1865267408a8509d1c8189b1e3bd3458f77d81` instead of `v1.3.3`

**Comment by InteNs** [comment]
Hey! I will test this next morning!

**Comment by InteNs** [comment]
@sondrelg It seems like more requests actually succeeded but it still throws the same timeout errors.
unfortunately it worked so well that i've now hit the rate limit for the github api ;)

**Comment by sondrelg** [comment]
Haha well that sounds like a partial success. What's the rate limit?

**Comment by InteNs** [comment]
it's 5000 requests per hour per user, i've ran the action twice, the action has 2 steps to delete versions (untagged and tagged) and it will do so for 14 packages in both steps, with the pagination limit of 100 versions thats 2800 requests at minimum per run.

**Comment by sondrelg** [comment]
Sounds like we *could* limit the total request for a single run to `< 5000`, but that beyond that users will need to be aware of their own limits. The action cannot know about other actions being run, or other calls being made right.

This also sounds like an issue one might see the first time one runs the action, but which will go away after that. I'm guessing you're not pumping out more than 5000 *new* images per hour, so running the action more frequently should resolve this for you, right?

**Comment by InteNs** [comment]
haha yeah this issue is only temporary until the backlog of old versions is deleted. (probably 500+ versions just sitting there for some of the packages)

#19 definitely improved the situation and resolves #18 for my use-case
